### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by earthkingman** [earthkingman/NodeJS-React-42StackOverFlow#225]
### 제목
Todo List
### 이슈에 대한 설명

- [ ] 42 로그인시 지팍에게 정보 공유 허용할지 메시지 뜨는거 수정

- [ ] 태그 ex # 제외 한걸로 수정하기

- [ ] 게시글 삭제 이후 메인 페이지로 이동

- [ ] 센트리 로깅 적용

- [ ] Aws 망할때 대비해서 데이터 백업

- [ ] App, index 분리

- [ ] Test code

- [ ] 리펙토링

- [ ] Error status 정확하게 구분하여 하도록 수정

- [ ] 메인페이지에서 미리보기 마크다운 문법 안보이도록 수정

- [ ] 좋아요 누를 때마다 조회수가 증가함 -> Detail page API 두개로 분리 (하나는 조회수 오르는 거, 하나는 정보 재요청하여 조회수 오르지 않는거)

- [ ] 닉네임 수정 기능의 익명성에 대하여

- [ ] 답변 삭제 이후 새로고침하지 않음

- [ ] 다른 유저의 정보를 조회하는 기능

- [ ] 질문글 상세보기 페이지에서 로그인시 메인 페이지로 이동하는거 수정

**Comment by hainho** [comment]
#229 sentry 적용

**Comment by hainho** [comment]
- [ ]  검색창에 입력 전에 회색 글씨로 "공백 없이 키워드로 검색해주세요!" 가이드 추가

**Comment by hainho** [comment]
- [ ] google analytics 적용
