### ISSUE TITLE
Todo 백엔드 정리

### ISSUE THREAD

**Issue by earthkingman** [earthkingman/NodeJS-React-42StackOverFlow#72]
### 제목
Todo 백엔드 정리
- [x] swagger

- [x] like API hook (현재 question 삭제시 다 삭제될때 like_count에 반영이 되지 않음)

- [x] 에러 클래스

- [x] 서비스 클래스

- [x] 베이스 클래스 상속

- [ ] 내일 깃헙 액션으로 ec2에 올라가도록

- [ ] 알림 api

- [x] 쿼리 두번 날리는거 줄이기

- [x] 페이지 정보 줄때 총 글 몇개인지 카운트해서 같이 리스폰

- [x] 유저에 포인트 추가

- [ ] 테스트 코드 작성

- [x] 주 기능은 해시태그로 검색
